FROM hashicorp/terraform:0.8.0
ADD https://github.com/mkuzmin/terraform-vsphere/releases/download/v1.0.pre2/terraform-provider-vmware.linux /usr/local/bin/terraform-provider-vsphere
RUN chmod +x /usr/local/bin/terraform-provider-vsphere
